apiVersion: 1

deleteDatasources:
   - name: Prometheus
     orgId: 1

datasources:
  - name: Prometheus
    type: prometheus
    orgId: 1
    url: http://monitoring:9090
    isDefault: true
    editable: false
