{
 "title": "home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ATOM/USDT Price",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "targets": [
    { "expr": "hedgedstaking_price", "legendFormat": "ATOM/USDC" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hedgedstaking_price", "legendFormat": "ATOM/USDC" }
   ]
  },
  {
   "title": "dYdX / Kraken ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "hedgedstaking_dYdX_Kraken_ratio",
     "legendFormat": "ratio"
    },
    {
     "expr": "hedgedstaking_dYdX_Kraken_ratio_high",
     "legendFormat": "high"
    },
    {
     "expr": "hedgedstaking_dYdX_Kraken_ratio_low",
     "legendFormat": "low"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedgedstaking_dYdX_Kraken_ratio",
     "legendFormat": "Ratio"
    }
   ]
  },
  {
   "title": "Total balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "hedgedstaking_balance_dYdX_total",
     "legendFormat": "dYdX"
    },
    {
     "expr": "hedgedstaking_balance_Kraken_total",
     "legendFormat": "Kraken"
    },
    {
     "expr": "hedgedstaking_balance_WALLET_USDC",
     "legendFormat": "wallet"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedgedstaking_balance_dYdX_total",
     "legendFormat": "Total dYdX, USDC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 14, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-hedgedstaking_balance_dYdX_shorted",
     "legendFormat": "Shorted dYdX, ATOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "-hedgedstaking_balance_dYdX_shorted*hedgedstaking_price / hedgedstaking_balance_dYdX_total",
     "legendFormat": "Leverage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedgedstaking_balance_Kraken_total",
     "legendFormat": "Total Kraken, USDC"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedgedstaking_balance_Kraken_staked_ATOM",
     "legendFormat": "Staked Kraken, ATOM"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hedgedstaking_balance_dYdX_total+hedgedstaking_balance_Kraken_total+hedgedstaking_balance_Binance_total+hedgedstaking_balance_wallet_USDC",
     "legendFormat": "Total, USDC"
    }
   ]
  },
  {
   "title": "USDC expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "increase(hedgedstaking_expense_ee_to_wallet_prim[10y]) + increase(hedgedstaking_expense_e1_to_wallet_prim[1y])",
     "legendFormat": "Binance+dYdX"
    }
   ]
  },
  {
   "title": "ATOM expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "increase(hedgedstaking_expense_e2_to_ee_sec[1y]) + increase(hedgedstaking_expense_ee_to_e2_sec[1y])",
     "legendFormat": "Binance+Kraken"
    }
   ]
  },
  {
   "title": "ETH expenses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "increase(hedgedstaking_expense_wallet_to_e1_gas[1y])+increase(hedgedstaking_expense_wallet_to_ee_gas[1y])",
     "legendFormat": "Wallet transfers"
    }
   ]
  },
  { "title": "dYdX", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "dYdX Balances",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "-hedgedstaking_balance_dYdX_shorted*hedgedstaking_price",
     "legendFormat": "shorted, USDC"
    },
    {
     "expr": "hedgedstaking_balance_dYdX_free",
     "legendFormat": "free, USDC"
    },
    {
     "expr": "hedgedstaking_balance_dYdX_total",
     "legendFormat": "total, USDC"
    }
   ]
  },
  {
   "title": "Leverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "-hedgedstaking_balance_dYdX_shorted*hedgedstaking_price / hedgedstaking_balance_dYdX_total",
     "legendFormat": "Leverage"
    }
   ]
  },
  { "title": "Kraken", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Balances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "hedgedstaking_balance_Kraken_total",
     "legendFormat": "total"
    },
    {
     "expr": "hedgedstaking_balance_Kraken_USDC",
     "legendFormat": "transf, USDC"
    },
    {
     "expr": "hedgedstaking_balance_Kraken_ZUSD",
     "legendFormat": "intermed, ZUSD"
    },
    {
     "expr": "hedgedstaking_balance_Kraken_unstaked_ATOM*hedgedstaking_price",
     "legendFormat": "unstaked"
    },
    {
     "expr": "hedgedstaking_balance_Kraken_staked_ATOM*hedgedstaking_price",
     "legendFormat": "staked"
    }
   ]
  }
 ]
}